//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GnWrappers {

#if GENIES_SDK && !GENIES_INTERNAL
internal class CancellationToken : global::System.IDisposable {
#else
public class CancellationToken : global::System.IDisposable {
#endif
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CancellationToken(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CancellationToken obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CancellationToken obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CancellationToken() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GnUtilsWrapperPINVOKE.delete_CancellationToken(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public CancellationToken() : this(GnUtilsWrapperPINVOKE.new_CancellationToken__SWIG_0(), true) {
  }

  public CancellationToken(CancellationToken arg0) : this(GnUtilsWrapperPINVOKE.new_CancellationToken__SWIG_1(CancellationToken.swigRelease(arg0)), true) {
    if (GnUtilsWrapperPINVOKE.SWIGPendingException.Pending) throw GnUtilsWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Cancel() {
    GnUtilsWrapperPINVOKE.CancellationToken_Cancel(swigCPtr);
  }

  public bool IsCancelled() {
    bool ret = GnUtilsWrapperPINVOKE.CancellationToken_IsCancelled(swigCPtr);
    return ret;
  }

  public bool RequestStop() {
    bool ret = GnUtilsWrapperPINVOKE.CancellationToken_RequestStop(swigCPtr);
    return ret;
  }

  public static CancellationToken Create() {
    CancellationToken ret = new CancellationToken(GnUtilsWrapperPINVOKE.CancellationToken_Create(), true);
    return ret;
  }

}

}
